config/routes.rb
Rails.application.routes.draw do

  get 'vehicles/new'

  root 'welcome#index'

  get 'sign_up' => 'users#new'
  post 'sign_up' => 'users#create'

  get 'profile' => 'users#show'
  get 'profile/edit' => 'users#edit'
  put 'profile' => 'users#update'

  post 'verify' => 'users#verify'

  delete 'sign_out' => 'user_sessions#destroy'

  resources :vehicles, only: [:new, :create, :edit, :update, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :vehicles, dependent: :destroy
  validates :mobile_number, uniqueness: true
  mount_uploader :photo, PhotoUploader

  acts_as_authentic do |c|
    c.validate_email_field = false
    c. validate_login_field = false
  end

  def generate_verification_code
    self.verification_code = rand(0000...9999).to_s.rjust(4, '0')
    self.is_verified = false
    save
  end

  def send_verification_code
    puts self.verification_code
  end

  def verify(entered_verification_code)
    update(is_verified: true) if self.verification_code == entered_verification_code
    self.is_verified
  end

  def verify(entered_verification_code)
    update(is_verified: true) if self.verification_code == entered_verification_code
    self.is_verified
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :user
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include UserSessionsHelper
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :not_authorized, only: [:show, :edit, :update]
  before_action :not_authenticated, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.find_or_create_by(users_params)
    if @user.valid?
      @user.generate_verification_code
      @user.send_verification_code
      log_out if logged_in?
    end
    respond_to do |format|
      format.js
    end
  end

  def verify
    @user = User.find_by(mobile_number: params[:hidden_mobile_number])
    if @user.verify(params[:verification_code])
      UserSession.create(@user, true)
    end
    respond_to do |format|
      format.js
    end
  end

  def show
  end

  def edit
  end

  def update
    if current_user.update_attributes(edit_users_params)
      redirect_to profile_path
    else
      render 'edit'
    end
  end

  private
    def users_params
      params.require(:user).permit(:mobile_number)
    end

    def edit_users_params
      params.require(:user).permit(:name, :email, :photo)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :not_authorized

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicles_params)
    @vehicle.user = current_user
    if @vehicle.save
      redirect_to profile_path
    else
      render 'new'
    end
  end

  def edit
    @vehicle = current_user.vehicles.find(params[:id])
  end


  def update
    @vehicle = current_user.vehicles.find(params[:id])
    if @vehicle.update_attributes(vehicles_params)
      redirect_to profile_path
    else
      render 'edit'
    end
  end

  def destroy
    @vehicle = current_user.vehicles.find(params[:id])
    @vehicle.destroy
    redirect_to profile_path
  end

  private

    def vehicles_params
      params.require(:vehicle).permit(:year, :make, :model, :license_plate, :photo)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to profile_path if logged_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
  private
  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
  end

  def log_out
    current_user_session.destroy
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def not_authorized
    unless logged_in?
      redirect_to root_path
    end
  end

  def not_authenticated
    redirect_to profile_path if logged_in?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<% if logged_in? %>
    <%= link_to 'Log out', sign_out_path, method: :delete %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsChallenge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

  <div class="container">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>

app/views/users/create.js.erb
$('#send-verification-code').hide()
$('#verify-verification-code').show()
$('#hidden_mobile_number').val('<%= @user.mobile_number %>')
$('#verify-mobile-number').html('<%= @user.mobile_number %>')
$('#mobile_number').focus()

app/views/users/edit.erb
<div id="user-profile">
  <h3>Edit Profile</h3>
  <%= form_for current_user, url: profile_path, method: 'put', html: { multipart: true } do |f| %>
      <%= render 'shared/errors', object: current_user %>

      <div>
        <img src="<%= current_user.photo.url %>" style="width: 10%; height: 10%"/>
      </div>
      <div>
        <%= f.file_field :photo %>
      </div>
      <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div>
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>
      <%= f.submit 'SAVE' %>
  <% end %>
</div>

app/views/users/new.html.erb
<div id="send-verification-code">
  <h3>Type your mobile number</h3>
  <%= form_for @user, url: sign_up_path, remote: true do |f| %>
      <div>
        <%= f.text_field :mobile_number %>
      </div>
      <%= f.submit 'VERIFY' %>
  <% end %>
</div>

<div id="verify-verification-code">
  <h3>We send a 4 digit verification code to <span id="verify-mobile-number"></span>. Enter it below.</h3>
  <%= form_tag verify_path, remote: true do %>
      <%= hidden_field_tag 'hidden_mobile_number', '' %>
      <div class="form-group">
        <%= text_field_tag :verification_code %>
      </div>
      <%= submit_tag 'SUBMIT'%>
  <% end %>
</div>

<div id="status-box">
  <p id="status-message">Sorry, that wasn't the right verification code.</p>
</div>

app/views/users/show.html.erb
<h3>Profile</h3>
<ul>
  <li><img src="<%= current_user.photo.url %>" style="width: 10%; height: 10%"/></li>
  <li><%= current_user.name %></li>
  <li><%= current_user.email %></li>
  <li><%= current_user.mobile_number %></li>
  <li><%= link_to 'EDIT', profile_edit_path %></li>
</ul>

<h3>Vehicles </h3>
<ul>
  <% current_user.vehicles.each do |vehicle| %>
      <%= render 'vehicles/vehicle', vehicle: vehicle %>
  <% end %>
</ul>
<%= link_to 'CREATE', new_vehicle_path %>

app/views/users/verify.js.erb
$('#status-box').hide()
<% if @user.is_verified %>
  window.location.href = '<%= profile_path %>'
<% else %>
  $('#status-box').fadeToggle()
<% end %>

app/views/vehicles/_vehicle.html.erb
<li>
  <%= vehicle.year %> | <%= vehicle.make %> |
  <%= vehicle.model %> | <%= vehicle.license_plate %>
  <%= link_to 'EDIT', edit_vehicle_path(vehicle) %> -
  <%= link_to 'DELETE', vehicle, :method => :delete %>
</li>

app/views/vehicles/edit.html.erb
<div id="user-profile">
  <h3>Edit Vehicle</h3>
  <%= form_for @vehicle do |f| %>
      <%= render 'shared/errors', object: @current_user %>

      <div>
        <img src="<%= @vehicle.photo.url %>" style="width: 10%; height: 10%"/>
      </div>
      <div>
        <%= f.file_field :photo %>
      </div>
      <div>
        <%= f.label :year %>
        <%= f.text_field :year %>
      </div>
      <div>
        <%= f.label :make %>
        <%= f.text_field :make %>
      </div>
      <div>
        <%= f.label :model %>
        <%= f.text_field :model %>
      </div>
      <div >
        <%= f.label :license_plate %>
        <%= f.text_field :license_plate  %>
      </div>
      <%= f.submit 'SAVE' %>
  <% end %>
</div>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<div>
  <%= form_for @vehicle do |f| %>
      <%= render 'shared/errors', object: @vehicle %>

      <div >
        <img src="<%= @vehicle.photo.url %>" style="width: 10%; height: 10%"/>
      </div>
      <div>
        <%= f.file_field :photo %>
      </div>
      <div>
        <%= f.label :year %>
        <%= f.text_field :year %>
      </div>
      <div>
        <%= f.label :make %>
        <%= f.text_field :make %>
      </div>
      <div>
        <%= f.label :model %>
        <%= f.text_field :model %>
      </div>
      <div >
        <%= f.label :license_plate %>
        <%= f.text_field :license_plate  %>
      </div>
      <%= submit_tag 'ADD VEHICLE' %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to Wagon</h1>

<ul>
  <li><%= link_to 'CREATE ACCOUNT', sign_up_path %></li>
  <li><%= link_to 'LOG IN', sign_up_path %></li>
</ul>